/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.irods.jargon.idrop.desktop.systraygui.viscomponents;

import java.util.ArrayList;
import java.util.List;
import org.irods.jargon.core.exception.JargonException;
import org.irods.jargon.core.pub.CollectionAO;
import org.irods.jargon.core.pub.domain.AvuData;
import org.irods.jargon.core.pub.io.IRODSFile;
import org.irods.jargon.core.pub.io.IRODSFileFactory;
import org.irods.jargon.core.query.AVUQueryElement;
import org.irods.jargon.core.query.AVUQueryElement.AVUQueryPart;
import org.irods.jargon.core.query.AVUQueryOperatorEnum;
import org.irods.jargon.core.query.JargonQueryException;
import org.irods.jargon.core.query.MetaDataAndDomainData;
import org.irods.jargon.core.utils.MiscIRODSUtils;
import org.irods.jargon.idrop.desktop.systraygui.ExperimentDialog;
import org.irods.jargon.idrop.desktop.systraygui.MessageManager;
import org.irods.jargon.idrop.desktop.systraygui.ToolsDialog;
import org.irods.jargon.idrop.desktop.systraygui.iDrop;
import static org.irods.jargon.idrop.desktop.systraygui.viscomponents.AddExperimentDialog.log;
import org.irods.jargon.idrop.finder.IRODSFinderDialog;
import org.openide.util.Exceptions;
import org.slf4j.LoggerFactory;

/**
 *
 * @author mconway
 */
public class AddImageDialog extends javax.swing.JDialog {

    iDrop idropGUI;
    String samplePrepDir;
    String sampleId;

    public static org.slf4j.Logger log = LoggerFactory
            .getLogger(AddImageDialog.class);

    /**
     * Creates new form AddExperimentDialog
     */
    public AddImageDialog(ExperimentDialog parent, boolean modal, iDrop idropGUI) {
        super(parent, modal);
        this.idropGUI = idropGUI;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlSelectParentDir = new javax.swing.JPanel();
        btnBrowseForDirectory = new javax.swing.JButton();
        txtParentDirectory = new javax.swing.JTextField();
        lblPrompt = new javax.swing.JLabel();
        scrollMetadata = new javax.swing.JScrollPane();
        pnlMetadata = new javax.swing.JPanel();
        lblImageId = new javax.swing.JLabel();
        txtImageId = new javax.swing.JTextField();
        lblMicroscopeUsed = new javax.swing.JLabel();
        txtMicroscopeUsed = new javax.swing.JTextField();
        lblResolution = new javax.swing.JLabel();
        txtResolution = new javax.swing.JTextField();
        lblNotes = new javax.swing.JLabel();
        scrollNotes = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        lblAcquisitionDate = new javax.swing.JLabel();
        txtAcquisitionDate = new javax.swing.JFormattedTextField();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        pnlBottom = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        bntSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlSelectParentDir.setLayout(new java.awt.GridBagLayout());

        btnBrowseForDirectory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/irods/jargon/idrop/desktop/systraygui/images/glyphicons_148_folder_flag.png"))); // NOI18N
        btnBrowseForDirectory.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.btnBrowseForDirectory.text")); // NOI18N
        btnBrowseForDirectory.setToolTipText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.btnBrowseForDirectory.toolTipText")); // NOI18N
        btnBrowseForDirectory.setName("btnBrowseForDirectory"); // NOI18N
        btnBrowseForDirectory.setPreferredSize(new java.awt.Dimension(110, 37));
        btnBrowseForDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseForDirectoryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlSelectParentDir.add(btnBrowseForDirectory, gridBagConstraints);

        txtParentDirectory.setColumns(30);
        txtParentDirectory.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.txtParentDirectory.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        pnlSelectParentDir.add(txtParentDirectory, gridBagConstraints);

        lblPrompt.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.lblPrompt.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        pnlSelectParentDir.add(lblPrompt, gridBagConstraints);

        getContentPane().add(pnlSelectParentDir, java.awt.BorderLayout.NORTH);

        pnlMetadata.setLayout(new java.awt.GridBagLayout());

        lblImageId.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.lblImageId.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlMetadata.add(lblImageId, gridBagConstraints);
        lblImageId.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.lblImageId.AccessibleContext.accessibleName")); // NOI18N

        txtImageId.setColumns(20);
        txtImageId.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.txtImageId.text")); // NOI18N
        txtImageId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImageIdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlMetadata.add(txtImageId, gridBagConstraints);

        lblMicroscopeUsed.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.lblMicroscopeUsed.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlMetadata.add(lblMicroscopeUsed, gridBagConstraints);

        txtMicroscopeUsed.setColumns(20);
        txtMicroscopeUsed.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.txtMicroscopeUsed.text")); // NOI18N
        txtMicroscopeUsed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMicroscopeUsedActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlMetadata.add(txtMicroscopeUsed, gridBagConstraints);

        lblResolution.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.lblResolution.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlMetadata.add(lblResolution, gridBagConstraints);

        txtResolution.setColumns(20);
        txtResolution.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.txtResolution.text")); // NOI18N
        txtResolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResolutionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlMetadata.add(txtResolution, gridBagConstraints);

        lblNotes.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.lblNotes.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlMetadata.add(lblNotes, gridBagConstraints);

        txtNotes.setColumns(30);
        txtNotes.setRows(5);
        scrollNotes.setViewportView(txtNotes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlMetadata.add(scrollNotes, gridBagConstraints);

        lblAcquisitionDate.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.lblAcquisitionDate.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlMetadata.add(lblAcquisitionDate, gridBagConstraints);

        txtAcquisitionDate.setColumns(12);
        txtAcquisitionDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtAcquisitionDate.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.txtAcquisitionDate.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlMetadata.add(txtAcquisitionDate, gridBagConstraints);

        lblColor.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.lblColor.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlMetadata.add(lblColor, gridBagConstraints);

        txtColor.setColumns(20);
        txtColor.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.txtColor.text")); // NOI18N
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlMetadata.add(txtColor, gridBagConstraints);

        scrollMetadata.setViewportView(pnlMetadata);

        getContentPane().add(scrollMetadata, java.awt.BorderLayout.CENTER);

        pnlBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/irods/jargon/idrop/desktop/systraygui/images/glyphicons_197_remove.png"))); // NOI18N
        btnCancel.setMnemonic('c');
        btnCancel.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.btnCancel.text")); // NOI18N
        btnCancel.setToolTipText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.btnCancel.toolTipText")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.setPreferredSize(new java.awt.Dimension(110, 37));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlBottom.add(btnCancel);

        bntSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/irods/jargon/idrop/desktop/systraygui/images/glyphicons_193_circle_ok.png"))); // NOI18N
        bntSave.setMnemonic('O');
        bntSave.setText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.bntSave.text")); // NOI18N
        bntSave.setToolTipText(org.openide.util.NbBundle.getMessage(AddImageDialog.class, "AddImageDialog.bntSave.toolTipText")); // NOI18N
        bntSave.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bntSave.setMaximumSize(null);
        bntSave.setMinimumSize(null);
        bntSave.setName("btnExit"); // NOI18N
        bntSave.setPreferredSize(new java.awt.Dimension(90, 37));
        bntSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaveActionPerformed(evt);
            }
        });
        pnlBottom.add(bntSave);

        getContentPane().add(pnlBottom, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseForDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseForDirectoryActionPerformed

        IRODSFinderDialog irodsFinderDialog = new IRODSFinderDialog(idropGUI, true, idropGUI.getiDropCore(), idropGUI.getIrodsAccount());
        irodsFinderDialog.setVisible(true);
        samplePrepDir = irodsFinderDialog.getSelectedAbsolutePath();

        if (samplePrepDir != null) {
            try {
                //txtParentDirectory.setText(MiscIRODSUtils.abbreviateFileName(samplePrepDir));
                txtParentDirectory.setText(samplePrepDir);
                CollectionAO collectionAO = idropGUI.getiDropCore().getIRODSAccessObjectFactory().getCollectionAO(idropGUI.getIrodsAccount());
                List<AVUQueryElement> query = new ArrayList<AVUQueryElement>();
                query.add(AVUQueryElement.instanceForValueQuery(AVUQueryPart.ATTRIBUTE, AVUQueryOperatorEnum.EQUAL, "SampleId"));
                List<MetaDataAndDomainData> result = collectionAO.findMetadataValuesByMetadataQueryForCollection(query, samplePrepDir);
                if (result.isEmpty()) {
                    log.warn("no sample for:{}", txtParentDirectory);
                    MessageManager.showWarning(this, "selected collection is not an sample preparation");
                }

                sampleId = result.get(0).getAvuValue();
                lblPrompt.setText("image is associated with sample preperation:" + sampleId);

            } catch (JargonException ex) {
                log.error("exception finding sample ", ex);
                MessageManager.showError(this, ex.getMessage());
            } catch (JargonQueryException ex) {
                log.error("exception finding sample", ex);
                MessageManager.showError(this, ex.getMessage());
            }

        }
    }//GEN-LAST:event_btnBrowseForDirectoryActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        dispose();

    }//GEN-LAST:event_btnCancelActionPerformed

    private void bntSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSaveActionPerformed
       
        dispose();
    }//GEN-LAST:event_bntSaveActionPerformed

    private void txtResolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResolutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResolutionActionPerformed

    private void txtMicroscopeUsedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMicroscopeUsedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMicroscopeUsedActionPerformed

    private void txtImageIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImageIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImageIdActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSave;
    private javax.swing.JButton btnBrowseForDirectory;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel lblAcquisitionDate;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblImageId;
    private javax.swing.JLabel lblMicroscopeUsed;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblPrompt;
    private javax.swing.JLabel lblResolution;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlMetadata;
    private javax.swing.JPanel pnlSelectParentDir;
    private javax.swing.JScrollPane scrollMetadata;
    private javax.swing.JScrollPane scrollNotes;
    private javax.swing.JFormattedTextField txtAcquisitionDate;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtImageId;
    private javax.swing.JTextField txtMicroscopeUsed;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtParentDirectory;
    private javax.swing.JTextField txtResolution;
    // End of variables declaration//GEN-END:variables
}
