/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.irods.jargon.idrop.desktop.systraygui;

import java.awt.Cursor;
import java.awt.GridBagConstraints;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.border.EmptyBorder;
import javax.swing.tree.TreePath;
import org.irods.jargon.core.exception.JargonException;
import org.irods.jargon.core.pub.io.IRODSFile;
import org.irods.jargon.datautils.tree.DiffTreePostProcessor;
import org.irods.jargon.datautils.tree.FileTreeDiffUtility;
import org.irods.jargon.datautils.tree.FileTreeDiffUtilityImpl;
import org.irods.jargon.datautils.tree.FileTreeModel;
import org.irods.jargon.idrop.desktop.systraygui.services.IRODSFileService;
import org.irods.jargon.idrop.desktop.systraygui.utils.MessageUtil;
import org.irods.jargon.idrop.desktop.systraygui.viscomponents.AddExperimentDialog;
import org.irods.jargon.idrop.desktop.systraygui.viscomponents.AddImageDialog;
import org.irods.jargon.idrop.desktop.systraygui.viscomponents.AddSampleDialog;
import org.irods.jargon.idrop.desktop.systraygui.viscomponents.CollapsiblePane;
import org.irods.jargon.idrop.desktop.systraygui.viscomponents.DiffViewData;
import org.irods.jargon.idrop.desktop.systraygui.viscomponents.HyperLinkButton;
import org.irods.jargon.idrop.desktop.systraygui.viscomponents.IRODSNode;
import org.irods.jargon.idrop.desktop.systraygui.viscomponents.IRODSOutlineModel;
import org.irods.jargon.idrop.desktop.systraygui.viscomponents.LocalFileNode;
import org.irods.jargon.idrop.exceptions.IdropException;
import org.slf4j.LoggerFactory;

/**
 *
 * @author lisa
 */
public class ExperimentDialog extends javax.swing.JDialog {

    private final IDROPCore idropCore;
    private final iDrop idropGui;

    public static org.slf4j.Logger log = LoggerFactory
            .getLogger(ExperimentDialog.class);

    /**
     * Creates new form AdvancedOptionsDialog
     */
    public ExperimentDialog(final iDrop parent,
            final boolean modal, final IDROPCore idropCore) {
        super(parent, modal);
        this.idropCore = idropCore;
        this.idropGui = parent;
        initComponents();

        setupToolsPanel();
        CollapsiblePane cpDataTools = new CollapsiblePane(pnlCollapsibles, "Experiment Tools", pnlExperiment);
        GridBagConstraints experimentToolsConstriants = new GridBagConstraints();
        experimentToolsConstriants.gridx = 0;
        experimentToolsConstriants.gridy = 0;
        experimentToolsConstriants.gridwidth = 1;
        experimentToolsConstriants.fill = GridBagConstraints.BOTH;
        experimentToolsConstriants.anchor = GridBagConstraints.NORTHWEST;
        experimentToolsConstriants.weightx = 1.0;
        experimentToolsConstriants.weighty = 1.0;
        JScrollPane sp = new JScrollPane();
        sp.setBorder(new EmptyBorder(0, 0, 0, 0));
        sp.setViewportView(cpDataTools);
        pnlCollapsibles.add(sp, experimentToolsConstriants);

    }

    private void setupToolsPanel() {
        HyperLinkButton btnAddExperiment = new HyperLinkButton("Create an experiment");
        btnAddExperiment.setName("create an experiment");
        btnAddExperiment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateExperimentActionPerformed(evt);
            }
        });
        pnlExperiment.add(btnAddExperiment);

        HyperLinkButton btnAddPrep = new HyperLinkButton("Set up a preparation");
        btnAddPrep.setName("btnAddPrep");
        btnAddPrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPreparationActionPerformed(evt);
            }
        });
        pnlExperiment.add(btnAddPrep);

        HyperLinkButton btnAddImage = new HyperLinkButton("Add image and channels");
        btnAddImage.setName("btnAddChannels");
        btnAddImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddImageActionPerformed(evt);
            }

        });
        pnlExperiment.add(btnAddImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlExperiment = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        pnlCollapsibles = new javax.swing.JPanel();
        pnlButtons = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bntSave = new javax.swing.JButton();

        pnlExperiment.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        pnlExperiment.setLayout(new java.awt.GridLayout(4, 1));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(ExperimentDialog.class, "ExperimentDialog.title_1")); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 300));

        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlCollapsibles.setLayout(new java.awt.GridBagLayout());
        pnlMain.add(pnlCollapsibles, java.awt.BorderLayout.CENTER);

        pnlButtons.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlButtons.setPreferredSize(new java.awt.Dimension(86, 50));
        pnlButtons.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        pnlButtons.add(jPanel1, gridBagConstraints);

        bntSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/irods/jargon/idrop/desktop/systraygui/images/glyphicons_193_circle_ok.png"))); // NOI18N
        bntSave.setMnemonic('O');
        bntSave.setText(org.openide.util.NbBundle.getMessage(ExperimentDialog.class, "ToolsDialog.btnExit.text")); // NOI18N
        bntSave.setToolTipText(org.openide.util.NbBundle.getMessage(ExperimentDialog.class, "ExperimentDialog.bntSave.toolTipText_1")); // NOI18N
        bntSave.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bntSave.setMaximumSize(null);
        bntSave.setMinimumSize(null);
        bntSave.setName("btnExit"); // NOI18N
        bntSave.setPreferredSize(new java.awt.Dimension(90, 37));
        bntSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlButtons.add(bntSave, gridBagConstraints);

        pnlMain.add(pnlButtons, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSaveActionPerformed
        dispose();
    }//GEN-LAST:event_bntSaveActionPerformed

    private void btnCreateExperimentActionPerformed(java.awt.event.ActionEvent evt) {
        AddExperimentDialog aed = new AddExperimentDialog(this, true, this.idropGui);
        aed.setVisible(true);
    }

    private void btnAddPreparationActionPerformed(java.awt.event.ActionEvent evt) {
        AddSampleDialog asd = new AddSampleDialog(this, true, this.idropGui);
        asd.setVisible(true);
    }

    private void btnAddImageActionPerformed(ActionEvent evt) {
        AddImageDialog asd = new AddImageDialog(this, true, this.idropGui);
        asd.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlCollapsibles;
    private javax.swing.JPanel pnlExperiment;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
