/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.irods.jargon.idrop.desktop.systraygui;

import org.irods.jargon.idrop.desktop.systraygui.viscomponents.IRODSTree;
import org.slf4j.LoggerFactory;

/**
 *
 * @author lisa
 */
public class IRODSInfoDialog extends javax.swing.JDialog {
    
    iDrop idropGUI;
    IRODSTree irodsTree;
    public static org.slf4j.Logger log = LoggerFactory.getLogger(IRODSTree.class);

    /**
     * Creates new form IRODSInfoDialog
     */
    public IRODSInfoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public IRODSInfoDialog(iDrop parent, boolean modal, final IRODSTree irodsTree) {
        super(parent, modal);
        initComponents();
        
        this.idropGUI = parent;
        this.irodsTree = irodsTree;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlIrodsInfo = new javax.swing.JPanel();
        tabInfo = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlInfoInner = new javax.swing.JPanel();
        pnlInfoIcon = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSelectedFileInfo = new javax.swing.JLabel();
        lblFilePathLabel = new javax.swing.JLabel();
        lblFileOrCollectionName = new javax.swing.JLabel();
        lblComment = new javax.swing.JLabel();
        scrollComment = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        lblTags = new javax.swing.JLabel();
        txtTags = new javax.swing.JTextField();
        btnUpdateInfo = new javax.swing.JButton();
        pnlFileInfoDemographics = new javax.swing.JPanel();
        lblInfoCreatedAt = new javax.swing.JLabel();
        lblInfoCreatedAtValue = new javax.swing.JLabel();
        lblInfoCreatedAtTimeValue = new javax.swing.JLabel();
        lblInfoUpdatedAt = new javax.swing.JLabel();
        lblInfoUpdatedAtValue = new javax.swing.JLabel();
        lblInfoUpdatedAtTimeValue = new javax.swing.JLabel();
        lblInfoLength = new javax.swing.JLabel();
        lblInfoLengthValue = new javax.swing.JLabel();
        lblInfoChecksum = new javax.swing.JLabel();
        lblInfoChecksumValue = new javax.swing.JLabel();
        lblOwnerNameLabel = new javax.swing.JLabel();
        lblOwnerName = new javax.swing.JLabel();
        lblOwnerZoneLabel = new javax.swing.JLabel();
        lblOwnerZone = new javax.swing.JLabel();
        lblCollectionTypeLabel = new javax.swing.JLabel();
        lblCollectionType = new javax.swing.JLabel();
        lblDataPathLabel = new javax.swing.JLabel();
        lblDataPath = new javax.swing.JLabel();
        lblDataReplicationStatusLabel = new javax.swing.JLabel();
        lblDataReplicationStatus = new javax.swing.JLabel();
        lblDataVersionLabel = new javax.swing.JLabel();
        lblDataVersion = new javax.swing.JLabel();
        lblDataTypeLabel = new javax.swing.JLabel();
        lblDataType = new javax.swing.JLabel();
        lblDataStatusLabel = new javax.swing.JLabel();
        lblDataStatus = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSaveAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlIrodsInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        pnlIrodsInfo.setLayout(new java.awt.BorderLayout());

        tabInfo.setToolTipText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.tabInfo.toolTipText")); // NOI18N

        pnlInfoInner.setLayout(new java.awt.GridBagLayout());

        pnlInfoIcon.setMaximumSize(new java.awt.Dimension(50, 50));
        pnlInfoIcon.setLayout(new java.awt.GridLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 204));
        pnlInfoIcon.add(jLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 2);
        pnlInfoInner.add(pnlInfoIcon, gridBagConstraints);

        lblSelectedFileInfo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblSelectedFileInfo.setForeground(java.awt.Color.blue);
        lblSelectedFileInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help-contents.png"))); // NOI18N
        lblSelectedFileInfo.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblSelectedFileInfo.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlInfoInner.add(lblSelectedFileInfo, gridBagConstraints);

        lblFilePathLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblFilePathLabel.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblFilePathLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlInfoInner.add(lblFilePathLabel, gridBagConstraints);

        lblFileOrCollectionName.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblFileOrCollectionName.text")); // NOI18N
        lblFileOrCollectionName.setMaximumSize(new java.awt.Dimension(900, 100));
        lblFileOrCollectionName.setMinimumSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 5, 0);
        pnlInfoInner.add(lblFileOrCollectionName, gridBagConstraints);

        lblComment.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblComment.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblComment.text")); // NOI18N
        lblComment.setToolTipText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblComment.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlInfoInner.add(lblComment, gridBagConstraints);

        scrollComment.setMinimumSize(null);

        txtComment.setColumns(30);
        txtComment.setRows(6);
        txtComment.setTabSize(5);
        txtComment.setToolTipText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.txtComment.toolTipText")); // NOI18N
        txtComment.setWrapStyleWord(true);
        txtComment.setMaximumSize(null);
        txtComment.setMinimumSize(null);
        txtComment.setPreferredSize(null);
        scrollComment.setViewportView(txtComment);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 0.2;
        pnlInfoInner.add(scrollComment, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        pnlInfoInner.add(filler4, gridBagConstraints);

        lblTags.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblTags.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblTags.text")); // NOI18N
        lblTags.setToolTipText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblTags.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlInfoInner.add(lblTags, gridBagConstraints);

        txtTags.setColumns(30);
        txtTags.setToolTipText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.txtTags.toolTipText")); // NOI18N
        txtTags.setMinimumSize(null);
        txtTags.setPreferredSize(null);
        txtTags.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTagsFocusLost(evt);
            }
        });
        txtTags.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTagsKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlInfoInner.add(txtTags, gridBagConstraints);

        btnUpdateInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dialog-accept.png"))); // NOI18N
        btnUpdateInfo.setMnemonic('u');
        btnUpdateInfo.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.btnUpdateInfo.text")); // NOI18N
        btnUpdateInfo.setToolTipText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.btnUpdateInfo.toolTipText")); // NOI18N
        btnUpdateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInfoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        pnlInfoInner.add(btnUpdateInfo, gridBagConstraints);

        pnlFileInfoDemographics.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlFileInfoDemographics.setLayout(new java.awt.GridBagLayout());

        lblInfoCreatedAt.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblInfoCreatedAt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblInfoCreatedAt.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblInfoCreatedAt.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 2, 0);
        pnlFileInfoDemographics.add(lblInfoCreatedAt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 5, 5, 0);
        pnlFileInfoDemographics.add(lblInfoCreatedAtValue, gridBagConstraints);

        lblInfoCreatedAtTimeValue.setToolTipText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblInfoCreatedAtTimeValue.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 5, 5, 0);
        pnlFileInfoDemographics.add(lblInfoCreatedAtTimeValue, gridBagConstraints);

        lblInfoUpdatedAt.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblInfoUpdatedAt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblInfoUpdatedAt.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblInfoUpdatedAt.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
        pnlFileInfoDemographics.add(lblInfoUpdatedAt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 2, 0);
        pnlFileInfoDemographics.add(lblInfoUpdatedAtValue, gridBagConstraints);

        lblInfoUpdatedAtTimeValue.setToolTipText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblInfoUpdatedAtTimeValue.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 2, 0);
        pnlFileInfoDemographics.add(lblInfoUpdatedAtTimeValue, gridBagConstraints);

        lblInfoLength.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblInfoLength.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblInfoLength.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblInfoLength.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        pnlFileInfoDemographics.add(lblInfoLength, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 2, 0);
        pnlFileInfoDemographics.add(lblInfoLengthValue, gridBagConstraints);

        lblInfoChecksum.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblInfoChecksum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblInfoChecksum.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblInfoChecksum.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 2, 0);
        pnlFileInfoDemographics.add(lblInfoChecksum, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 2, 0);
        pnlFileInfoDemographics.add(lblInfoChecksumValue, gridBagConstraints);

        lblOwnerNameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblOwnerNameLabel.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblOwnerNameLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 2, 0);
        pnlFileInfoDemographics.add(lblOwnerNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 2, 2, 0);
        pnlFileInfoDemographics.add(lblOwnerName, gridBagConstraints);

        lblOwnerZoneLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblOwnerZoneLabel.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblOwnerZoneLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 26, 2, 0);
        pnlFileInfoDemographics.add(lblOwnerZoneLabel, gridBagConstraints);

        lblOwnerZone.setToolTipText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblOwnerZone.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        pnlFileInfoDemographics.add(lblOwnerZone, gridBagConstraints);

        lblCollectionTypeLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblCollectionTypeLabel.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblCollectionTypeLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        pnlFileInfoDemographics.add(lblCollectionTypeLabel, gridBagConstraints);

        lblCollectionType.setToolTipText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblCollectionType.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        pnlFileInfoDemographics.add(lblCollectionType, gridBagConstraints);

        lblDataPathLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblDataPathLabel.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblDataPathLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        pnlFileInfoDemographics.add(lblDataPathLabel, gridBagConstraints);

        lblDataPath.setToolTipText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblDataPath.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 10);
        pnlFileInfoDemographics.add(lblDataPath, gridBagConstraints);

        lblDataReplicationStatusLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblDataReplicationStatusLabel.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblDataReplicationStatusLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlFileInfoDemographics.add(lblDataReplicationStatusLabel, gridBagConstraints);

        lblDataReplicationStatus.setToolTipText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblDataReplicationStatus.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 2, 0, 10);
        pnlFileInfoDemographics.add(lblDataReplicationStatus, gridBagConstraints);

        lblDataVersionLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblDataVersionLabel.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblDataVersionLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 2, 0);
        pnlFileInfoDemographics.add(lblDataVersionLabel, gridBagConstraints);

        lblDataVersion.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblDataVersion.text")); // NOI18N
        lblDataVersion.setToolTipText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblDataVersion.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 2, 0, 10);
        pnlFileInfoDemographics.add(lblDataVersion, gridBagConstraints);

        lblDataTypeLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblDataTypeLabel.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblDataTypeLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlFileInfoDemographics.add(lblDataTypeLabel, gridBagConstraints);

        lblDataType.setToolTipText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblDataType.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        pnlFileInfoDemographics.add(lblDataType, gridBagConstraints);

        lblDataStatusLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblDataStatusLabel.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblDataStatusLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlFileInfoDemographics.add(lblDataStatusLabel, gridBagConstraints);

        lblDataStatus.setToolTipText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.lblDataStatus.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 10);
        pnlFileInfoDemographics.add(lblDataStatus, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 2, 6, 2);
        pnlInfoInner.add(pnlFileInfoDemographics, gridBagConstraints);

        jScrollPane1.setViewportView(pnlInfoInner);

        tabInfo.addTab(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.jScrollPane1.TabConstraints.tabTitle"), jScrollPane1); // NOI18N
        tabInfo.addTab(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.jTabbedPane1.TabConstraints.tabTitle"), jTabbedPane1); // NOI18N
        tabInfo.addTab(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.jTabbedPane2.TabConstraints.tabTitle"), jTabbedPane2); // NOI18N

        pnlIrodsInfo.add(tabInfo, java.awt.BorderLayout.CENTER);

        jPanel1.add(pnlIrodsInfo, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(460, 60));

        btnCancel.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.btnCancel.text")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel);

        btnSaveAll.setText(org.openide.util.NbBundle.getMessage(IRODSInfoDialog.class, "IRODSInfoDialog.btnSaveAll.text")); // NOI18N
        btnSaveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAllActionPerformed(evt);
            }
        });
        jPanel2.add(btnSaveAll);

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTagsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTagsFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTagsFocusLost

    private void txtTagsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTagsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTagsKeyPressed

    private void btnUpdateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateInfoActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAllActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSaveAllActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSaveAll;
    private javax.swing.JButton btnUpdateInfo;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblCollectionType;
    private javax.swing.JLabel lblCollectionTypeLabel;
    private javax.swing.JLabel lblComment;
    private javax.swing.JLabel lblDataPath;
    private javax.swing.JLabel lblDataPathLabel;
    private javax.swing.JLabel lblDataReplicationStatus;
    private javax.swing.JLabel lblDataReplicationStatusLabel;
    private javax.swing.JLabel lblDataStatus;
    private javax.swing.JLabel lblDataStatusLabel;
    private javax.swing.JLabel lblDataType;
    private javax.swing.JLabel lblDataTypeLabel;
    private javax.swing.JLabel lblDataVersion;
    private javax.swing.JLabel lblDataVersionLabel;
    private javax.swing.JLabel lblFileOrCollectionName;
    private javax.swing.JLabel lblFilePathLabel;
    private javax.swing.JLabel lblInfoChecksum;
    private javax.swing.JLabel lblInfoChecksumValue;
    private javax.swing.JLabel lblInfoCreatedAt;
    private javax.swing.JLabel lblInfoCreatedAtTimeValue;
    private javax.swing.JLabel lblInfoCreatedAtValue;
    private javax.swing.JLabel lblInfoLength;
    private javax.swing.JLabel lblInfoLengthValue;
    private javax.swing.JLabel lblInfoUpdatedAt;
    private javax.swing.JLabel lblInfoUpdatedAtTimeValue;
    private javax.swing.JLabel lblInfoUpdatedAtValue;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblOwnerNameLabel;
    private javax.swing.JLabel lblOwnerZone;
    private javax.swing.JLabel lblOwnerZoneLabel;
    private javax.swing.JLabel lblSelectedFileInfo;
    private javax.swing.JLabel lblTags;
    private javax.swing.JPanel pnlFileInfoDemographics;
    private javax.swing.JPanel pnlInfoIcon;
    private javax.swing.JPanel pnlInfoInner;
    private javax.swing.JPanel pnlIrodsInfo;
    private javax.swing.JScrollPane scrollComment;
    private javax.swing.JTabbedPane tabInfo;
    private javax.swing.JTextArea txtComment;
    private javax.swing.JTextField txtTags;
    // End of variables declaration//GEN-END:variables
}
