/*
 * SynchSetupDialog.java
 *
 * Created on Mar 22, 2011, 10:34:06 AM
 */
package org.irods.jargon.idrop.desktop.systraygui;

import java.util.logging.Level;
import java.util.logging.Logger;

import org.irods.jargon.core.exception.DuplicateDataException;
import org.irods.jargon.core.exception.JargonException;
import org.irods.jargon.core.pub.IRODSFileSystem;
import org.irods.jargon.datautils.synchproperties.SynchPropertiesService;
import org.irods.jargon.datautils.synchproperties.SynchPropertiesServiceImpl;
import org.irods.jargon.datautils.tree.FileTreeDiffUtilityImpl;
import org.irods.jargon.idrop.exceptions.IdropRuntimeException;
import org.irods.jargon.transfer.synch.SynchronizeProcessor;
import org.irods.jargon.transfer.synch.SynchronizeProcessorImpl;

/**
 * 
 * @author mikeconway
 */
public class SynchSetupDialog extends javax.swing.JDialog {

    private final IDROPCore idropCore;
    private final IRODSFileSystem irodsFileSystem;
    private final SynchPropertiesService synchPropertiesService;

    /** Creates new form SynchSetupDialog */
    public SynchSetupDialog(final iDrop parent, final IDROPCore idropCore,
            final IRODSFileSystem irodsFileSystem) {
        super(parent, false);
        this.idropCore = idropCore;
        this.irodsFileSystem = irodsFileSystem;
        initComponents();
        try {
            synchPropertiesService = new SynchPropertiesServiceImpl(
                    irodsFileSystem.getIRODSAccessObjectFactory(),
                    idropCore.getIrodsAccount());
        } catch (JargonException ex) {
            Logger.getLogger(SynchSetupDialog.class.getName()).log(
                    Level.SEVERE, null, ex);
            throw new IdropRuntimeException(
                    "unable to build synchPropertiesService", ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		lblDeviceName = new javax.swing.JLabel();
		txtDeviceName = new javax.swing.JTextField();
		lblDeviceName1 = new javax.swing.JLabel();
		txtIrodsPath = new javax.swing.JTextField();
		lblDeviceName2 = new javax.swing.JLabel();
		localPath = new javax.swing.JTextField();
		btnAdd = new javax.swing.JButton();
		btnSynch = new javax.swing.JButton();
		btnUpdateTimestamps = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		lblDeviceName.setText("Device Name:");

		lblDeviceName1.setText("iRODS Path:");

		lblDeviceName2.setText("Local Path:");

		btnAdd.setText("Add Device");
		btnAdd.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(final java.awt.event.ActionEvent evt) {
				btnAddActionPerformed(evt);
			}
		});

		btnSynch.setText("Synch");
		btnSynch.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(final java.awt.event.ActionEvent evt) {
				btnSynchActionPerformed(evt);
			}
		});

		btnUpdateTimestamps.setText("Update Timestamps");
		btnUpdateTimestamps
				.addActionListener(new java.awt.event.ActionListener() {
					@Override
					public void actionPerformed(
							final java.awt.event.ActionEvent evt) {
						btnUpdateTimestampsActionPerformed(evt);
					}
				});

		jLabel1.setText("Testing only.....");

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(org.jdesktop.layout.GroupLayout.TRAILING,
						layout.createSequentialGroup()
								.add(layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.TRAILING)
										.add(layout.createSequentialGroup()
												.addContainerGap()
												.add(btnUpdateTimestamps))
										.add(layout
												.createSequentialGroup()
												.add(47, 47, 47)
												.add(layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.LEADING,
																		false)
																.add(layout
																		.createSequentialGroup()
																		.add(lblDeviceName1)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.add(txtIrodsPath,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				394,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																.add(layout
																		.createSequentialGroup()
																		.add(lblDeviceName)
																		.add(18,
																				18,
																				18)
																		.add(txtDeviceName,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				394,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
														.add(org.jdesktop.layout.GroupLayout.TRAILING,
																layout.createSequentialGroup()
																		.add(lblDeviceName2)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				36,
																				Short.MAX_VALUE)
																		.add(layout
																				.createParallelGroup(
																						org.jdesktop.layout.GroupLayout.LEADING,
																						false)
																				.add(layout
																						.createSequentialGroup()
																						.add(btnAdd)
																						.addPreferredGap(
																								org.jdesktop.layout.LayoutStyle.RELATED,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.add(btnSynch))
																				.add(localPath,
																						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																						394,
																						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
								.add(279, 279, 279))
				.add(layout
						.createSequentialGroup()
						.add(67, 67, 67)
						.add(jLabel1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								604,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(153, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(jLabel1)
						.add(4, 4, 4)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(lblDeviceName)
								.add(txtDeviceName,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(lblDeviceName1)
								.add(txtIrodsPath,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(lblDeviceName2)
								.add(localPath,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.add(18, 18, 18)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(btnAdd).add(btnSynch))
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.UNRELATED)
						.add(btnUpdateTimestamps)
						.addContainerGap(25, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
        try {
            SynchPropertiesService synchPropertiesService = new SynchPropertiesServiceImpl(
                    irodsFileSystem.getIRODSAccessObjectFactory(),
                    idropCore.getIrodsAccount());
            synchPropertiesService.addSynchDeviceForUserAndIrodsAbsolutePath(
                    idropCore.getIrodsAccount().getUserName(), txtDeviceName.getText().trim(), txtIrodsPath.getText().trim(),
                    localPath.getText().trim());
        } catch (DuplicateDataException ex) {
            Logger.getLogger(SynchSetupDialog.class.getName()).log(
                    Level.SEVERE, null, ex);
        } catch (JargonException ex) {
            Logger.getLogger(SynchSetupDialog.class.getName()).log(
                    Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_btnAddActionPerformed

    private void btnSynchActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSynchActionPerformed

        try {
            SynchronizeProcessor synchProcessor = new SynchronizeProcessorImpl();
            synchProcessor.setFileTreeDiffUtility(new FileTreeDiffUtilityImpl(
                    idropCore.getIrodsAccount(), irodsFileSystem.getIRODSAccessObjectFactory()));
            synchProcessor.setIrodsAccessObjectFactory(irodsFileSystem.getIRODSAccessObjectFactory());
            synchProcessor.setIrodsAccount(idropCore.getIrodsAccount());
            synchProcessor.setTransferManager(idropCore.getTransferManager());
            synchProcessor.setSynchPropertiesService(synchPropertiesService);
            // FIXME: refactor to not pass this stuff in, or alt method
            synchProcessor.synchronizeLocalToIRODS(txtDeviceName.getText().trim(), txtIrodsPath.getText().trim());
        } catch (JargonException ex) {
            Logger.getLogger(SynchSetupDialog.class.getName()).log(
                    Level.SEVERE, null, ex);
        } finally {
            irodsFileSystem.closeAndEatExceptions();
        }

    }// GEN-LAST:event_btnSynchActionPerformed

    private void btnUpdateTimestampsActionPerformed(
            final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateTimestampsActionPerformed
        try {
            SynchronizeProcessor synchProcessor = new SynchronizeProcessorImpl();
            synchProcessor.setFileTreeDiffUtility(new FileTreeDiffUtilityImpl(
                    idropCore.getIrodsAccount(), irodsFileSystem.getIRODSAccessObjectFactory()));
            synchProcessor.setIrodsAccessObjectFactory(irodsFileSystem.getIRODSAccessObjectFactory());
            synchProcessor.setIrodsAccount(idropCore.getIrodsAccount());
            synchProcessor.setTransferManager(idropCore.getTransferManager());
            synchProcessor.setSynchPropertiesService(synchPropertiesService);
            synchProcessor.getTimestampsAndUpdateSynchDataInIRODS(idropCore.getIrodsAccount().getUserName(), txtDeviceName.getText().trim(), txtIrodsPath.getText().trim());
        } catch (JargonException ex) {
            Logger.getLogger(SynchSetupDialog.class.getName()).log(
                    Level.SEVERE, null, ex);
        } finally {
            irodsFileSystem.closeAndEatExceptions();
        }

    }// GEN-LAST:event_btnUpdateTimestampsActionPerformed
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAdd;

	private javax.swing.JButton btnSynch;

	private javax.swing.JButton btnUpdateTimestamps;

	private javax.swing.JLabel jLabel1;

	private javax.swing.JLabel lblDeviceName;

	private javax.swing.JLabel lblDeviceName1;

	private javax.swing.JLabel lblDeviceName2;

	private javax.swing.JTextField localPath;

	private javax.swing.JTextField txtDeviceName;

	private javax.swing.JTextField txtIrodsPath;
	// End of variables declaration//GEN-END:variables
}
